### PR TITLE
Make link for getting a sandbox more obvious.

### PR DESCRIPTION
**Pull request by obmarg**
Took me a while to figure out I was meant to click on the word "Connect"
to find out how to get a sandbox.

### CODE REVIEW

**Comment by carlos-alberto** [comment]
:shipit:

**Comment by obmarg** [comment]
Any opinions on opening these links in a new window?  I think it might help - the "getting a sandbox URL" process is not a 2 second job, by which point you might have forgotten that you need to hit back in that tab to get back where you were...

**Comment by carlos-alberto** [comment]
Yeah seems like a reasonable idea. Is that possible with markdown?

**Comment by obmarg** [comment]
It's non standard, but it's possible with some flavours

**Comment by villaaston** [comment]
Will need to update here too: https://github.com/rolepoint/connect-examples/blob/master/insert-candidate-and-track-status/python/README.md

**Pull request merged**
